-
  name: 'FrontendLogin Api'
  uriPattern: 'api/user/{@controller}(/{@action})'
  defaults:
    '@package': 'UpAssist.Neos.FrontendLogin'
    '@controller': 'Login'
    '@action': 'status'
    '@format': 'html'
  appendExceedingArguments: TRUE
