TYPO3:

  Flow:
    security:
      authentication:
        providers:
          'Typo3BackendProvider':
            requestPatterns:
              'UpAssist\Neos\FrontendLogin\Security\NeosRequestPattern': 'backend'
          'UpAssist.Neos.FrontendLogin:Frontend':
            provider: 'PersistedUsernamePasswordProvider'
            requestPatterns:
              'UpAssist\Neos\FrontendLogin\Security\NeosRequestPattern': 'frontend'

    aop:
      globalObjects:
        'frontendUserService': 'UpAssist\Neos\FrontendLogin\Domain\Service\FrontendUserService'

  Neos:
    typoScript:
      autoInclude:
        'UpAssist.Neos.FrontendLogin': TRUE
      userInterface:
         translation:
           autoInclude:
             'UpAssist.Neos.FrontendLogin': ['NodeTypes/*']

    modules:
      frontendUsers:
        label: 'TYPO3.Neos:Modules:users.label'
        controller: 'UpAssist\Neos\FrontendLogin\Controller\Module\UsersController'
        description: 'TYPO3.Neos:Modules:users.description'
        icon: 'icon-group'
        actions:
          new:
            label: 'TYPO3.Neos:Modules:users.actions.new.label'
            title: 'TYPO3.Neos:Modules:users.actions.new.title'
        privilegeTarget: 'UpAssist.Neos.FrontendLogin:CanAdministerUsers'