
Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'UpAssist.Neos.FrontendLogin:Backend':
                pattern: UpAssist\Neos\FrontendLogin\Security\NeosRequestPattern
          'UpAssist.Neos.FrontendLogin:Frontend':
            provider: PersistedUsernamePasswordProvider
            requestPatterns:
              'UpAssist.Neos.FrontendLogin:Frontend':
                pattern: UpAssist\Neos\FrontendLogin\Security\NeosRequestPattern
                patternOptions:
                  matchFrontend: true

    aop:
      globalObjects:
        frontendUserService: UpAssist\Neos\FrontendLogin\Domain\Service\FrontendUserService
  Neos:
    modules:
      frontendUsers:
        label: 'Neos.Neos:Modules:users.label'
        controller: UpAssist\Neos\FrontendLogin\Controller\Module\UsersController
        description: 'Neos.Neos:Modules:users.description'
        icon: icon-group
        actions:
          new:
            label: 'Neos.Neos:Modules:users.actions.new.label'
            title: 'Neos.Neos:Modules:users.actions.new.title'
        privilegeTarget: 'UpAssist.Neos.FrontendLogin:CanAdministerUsers'
    fusion:
      autoInclude:
        UpAssist.Neos.FrontendLogin: true
      userInterface:
        translation:
          autoInclude:
            UpAssist.Neos.FrontendLogin:
              - 'NodeTypes/*'
