UpAssist:
  Neos:
    FrontendLogin:
      # Set this to the package of your choice if you want to override the flashmessages from the login controller.
      # Translation labels should be in the Main.xlf file.
      translationPackage: 'UpAssist.Neos.FrontendLogin'
      # Set this like so to add a form selector for selecting a role upon creating a user.
      roleIdentifiers: []
        # 'UpAssist.Neos.FrontendLogin:User': 'User'
Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'UpAssist.Neos.FrontendLogin:Backend':
                pattern: UpAssist\Neos\FrontendLogin\Security\NeosRequestPattern
          'UpAssist.Neos.FrontendLogin:Frontend':
            label: 'Frontend Authentication'
            provider: PersistedUsernamePasswordProvider
            requestPatterns:
              'UpAssist.Neos.FrontendLogin:Frontend':
                pattern: UpAssist\Neos\FrontendLogin\Security\NeosRequestPattern
                patternOptions:
                  matchFrontend: true

    aop:
      globalObjects:
        frontendUserService: UpAssist\Neos\FrontendLogin\Domain\Service\FrontendUserService
    mvc:
      routes:
        UpAssist.Neos.FrontendLogin: true
  Neos:
    fusion:
      autoInclude:
        UpAssist.Neos.FrontendLogin: true
      userInterface:
        translation:
          autoInclude:
            UpAssist.Neos.FrontendLogin:
              - '*'
    nodeTypes:
      groups:
        frontendLogin:
          label: 'UpAssist.Neos.FrontendLogin:Main:nodeTypes.groups.frontendLogin'
          collapsed: true
